changesetIgnorePatterns:
  - "**/__testfixtures__/*.{ts,tsx}"

compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

pnpEnableEsmLoader: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
